version: "3"
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    #allows us to get local changes into the image dir real-time
    #automatically update the container
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
